title: §l§dMerci§fNetwork
exit-button: §4§lEXIT
content: Manage easily your island!
create-content: basic

#Main form config
create-island: Create an island
join-island: Join your island
see-category: See your category
see-blocks: See blocks placed
disband-island: Disband your island

#Create form config
basic: Basic